NAME=chimera_disorder_free
VIEWPDF=evince
BIBTEXSRCS=chimera.bib
USE_PDFLATEX=1
CLEAN_FILES+=chimera_disorder_free.synctex.gz chimera_disorder_freeNotes.bib chimera_disorder_free.tar.gz *.bak *.tmp
EXTRA_DIST+=*.jpeg drive_distribution.pdf quasienergy_8.pdf sz_t_strongweakJ_ea_N_8.pdf clean_J_strong_MzAB_betas.pdf entangEntrp.pdf robustness_N_8.pdf

include /usr/share/latex-mk/latex.gmk
