NAME=chimera
VIEWPDF=evince
BIBTEXSRCS=chimera.bib
USE_PDFLATEX=1
CLEAN_FILES+=chimera.synctex.gz chimeraNotes.bib chimera.fdb_latexmk chimera.tar.gz *.bak *.tmp
EXTRA_DIST+=*.pdf iop* 

include /usr/share/latex-mk/latex.gmk
