NAME=chimera_disorder_free
VIEWPDF=evince
BIBTEXSRCS=chimera.bib
USE_PDFLATEX=1
CLEAN_FILES+=chimera_disorder_free.synctex.gz chimera_disorder_freeNotes.bib chimera_disorder_free.tar.gz *.bak *.tmp
EXTRA_DIST+=*.pdf

include /usr/share/latex-mk/latex.gmk
