NAME=BJ14850_chimera letter_to_editor
VIEWPDF=evince
BIBTEXSRCS=chimera_refs.bib
USE_PDFLATEX=1
CLEAN_FILES+=*.synctex.gz BJ14850_chimeraNotes.bib BJ14850_chimera.tar.gz *.bak *.tmp

include /usr/share/latex-mk/latex.gmk
